### DISCUSSION TITLE
ThemeLoader.php

### DISCUSSION THREAD

**Discussion by VasylKyryliuk** [agence-adeliom/sylius-tailwindcss-theme#75] [Q&A] [answered]
Hey guys. I'm going trough the installation of Tailwind theme on Sylius 2. 
I'm using this documentation steps (https://github.com/agence-adeliom/sylius-tailwindcss-theme/blob/2.x/docs/installation_as_package.md).

On step number 3 with using the composer file i get the error in console when i run `bin/console cache:clean`:

```
In ThemeLoader.php line 118:
                                                                                                                    
  Unexisting theme "agence-adeliom/sylius-tailwindcss-theme" is required by "acme/sylius-tailwindcss-child-theme".  
```
The same issue i have even if i done with all the steps in documentation.
I double checked the vendor folder, "agence-adeliom/sylius-tailwindcss-theme"  is available. 
Has somebody faced with this issue?

**Comment by VasylKyryliuk** [comment, marked as answer]
I found the solution:

go to file `config/packages/sylius_theme.yaml`

change the original part of code:


```
sylius_theme:
    sources:
        filesystem:
            scan_depth: 1
            directories:
                - "%kernel.project_dir%/themes"
```


to:

```
sylius_theme:
    sources:
        filesystem: ~
```
